/**
 * Database row types — mirrors the Supabase schema exactly.
 *
 * Use these everywhere (components, services, server actions) so the app stays
 * type-safe against the database. Generated by hand to stay lean; regenerate
 * with `supabase gen types typescript` if columns change.
 */

// ─── Enums ─────────────────────────────────────────────────────────────────

export type UserRole = "super_admin" | "admin" | "editor";
export type ExperienceType = "work" | "education" | "certification";
export type SocialPlatform =
  | "github" | "linkedin" | "twitter" | "instagram" | "youtube"
  | "dribbble" | "behance" | "website" | "email";

// ─── Tables ───────────────────────────────────────────────────────────────

export interface Profile {
  id: string;
  email: string;
  name: string | null;
  avatar_url: string | null;
  role: UserRole;
  created_at: string;
  updated_at: string;
}

export interface SiteSettings {
  id: 1; // singleton
  site_title: string;
  site_description: string;
  contact_email: string | null;
  resume_url: string | null;
  resume_filename: string | null;
  resume_updated_at: string | null;
  default_theme: "light" | "dark" | "system";
  /** Controls which animation style visitors see. Defaults to "new" if column absent. */
  animation_style?: "new" | "classic" | "minimal" | "fluid" | "magnetic";
  /** Admin-selected UI/UX Design theme for the entire website (Minimalist + 5 additional themes). */
  ui_design?: "minimalist" | "obsidian" | "nordic" | "tokyo" | "monolith" | "aurora";
  created_at: string;
  updated_at: string;
}

export interface HomeContent {
  id: 1;
  hero_name: string;
  hero_role: string;
  hero_intro: string;
  hero_image_url: string | null;
  primary_cta_label: string;
  primary_cta_href: string;
  secondary_cta_label: string;
  secondary_cta_href: string;
  about_preview: string;
  contact_cta: string;
  created_at: string;
  updated_at: string;
}

export interface AboutContent {
  id: 1;
  headline: string;
  bio: string;
  overview: string;
  photo_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface Skill {
  id: string;
  name: string;
  category: string;
  proficiency: number | null;
  order: number;
  created_at: string;
  updated_at: string;
}

export interface Experience {
  id: string;
  type: ExperienceType;
  role: string;
  organization: string;
  location: string | null;
  start_date: string;
  end_date: string | null;
  current: boolean;
  description: string;
  url: string | null;
  order: number;
  published: boolean;
  created_at: string;
  updated_at: string;
}

export interface Project {
  id: string;
  slug: string;
  title: string;
  summary: string;
  description: string;
  cover_url: string | null;
  gallery: string[];
  tags: string[];
  live_url: string | null;
  source_url: string | null;
  featured: boolean;
  published: boolean;
  order: number;
  created_at: string;
  updated_at: string;
}

export interface SocialLink {
  id: string;
  platform: SocialPlatform;
  label: string;
  url: string;
  order: number;
  created_at: string;
  updated_at: string;
}

export interface SeoMetadata {
  page_key: string;
  title: string;
  description: string;
  keywords: string[];
  og_image_url: string | null;
  canonical_url: string | null;
  updated_at: string;
}

export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  subject: string;
  message: string;
  is_read: boolean;
  created_at: string;
}

export interface Certification {
  id: string;
  title: string;
  issuer: string;
  issue_date: string | null;
  credential_link: string | null;
  certificate_path: string | null;
  published: boolean;
  order: number;
  created_at: string;
  updated_at: string;
}

export interface Testimonial {
  id: string;
  quote: string;
  author_name: string;
  author_role: string;
  company: string | null;
  avatar_url: string | null;
  featured: boolean;
  order: number;
  created_at: string;
  updated_at: string;
}

export interface ServiceOffering {
  id: string;
  title: string;
  tagline: string;
  description: string;
  deliverables: string[];
  price_range: string | null;
  icon: string | null;
  active: boolean;
  order: number;
  created_at: string;
  updated_at: string;
}

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  cover_url: string | null;
  tags: string[];
  reading_time_minutes: number;
  published: boolean;
  featured: boolean;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface AuditLog {
  id: string;
  action: string;
  module: "projects" | "content" | "settings" | "security" | "messages" | "testimonials" | "services" | "posts" | "notes";
  details: string;
  user_email: string;
  created_at: string;
}

export interface AdminNote {
  id: string;
  title: string;
  content: string;
  pinned: boolean;
  completed: boolean;
  color: string | null;
  image_url?: string | null;
  created_at: string;
  updated_at: string;
}

export interface PublicNotification {
  id: string;
  title: string;
  message: string;
  type: "info" | "announcement" | "alert" | "success";
  active: boolean;
  created_at: string;
  updated_at: string;
}


